const carData = [
    {
      id: 1,
      brand: 'Toyota',
      model: 'Corolla',
      year: 2020,
      price: 25000,
    },
    {
      id: 2,
      brand: 'Honda',
      model: 'Civic',
      year: 2019,
      price: 22000,
    },
    {
      id: 3,
      brand: 'Ford',
      model: 'Mustang',
      year: 2021,
      price: 35000,
    },
    {
      id: 4,
      brand: 'Chevrolet',
      model: 'Camaro',
      year: 2018,
      price: 30000,
    },
    {
      id: 5,
      brand: 'BMW',
      model: '3 Series',
      year: 2020,
      price: 40000,
    },
    {
      id: 6,
      brand: 'Mercedes-Benz',
      model: 'C-Class',
      year: 2019,
      price: 45000,
    },
    {
      id: 7,
      brand: 'Audi',
      model: 'A4',
      year: 2021,
      price: 42000,
    },
    {
      id: 8,
      brand: 'Lexus',
      model: 'ES',
      year: 2020,
      price: 38000,
    },
    {
      id: 9,
      brand: 'Tesla',
      model: 'Model 3',
      year: 2022,
      price: 55000,
    },
    {
      id: 10,
      brand: 'Volkswagen',
      model: 'Golf',
      year: 2019,
      price: 20000,
    },
    {
      id: 11,
      brand: 'Subaru',
      model: 'Outback',
      year: 2021,
      price: 32000,
    },
    {
      id: 12,
      brand: 'Hyundai',
      model: 'Elantra',
      year: 2018,
      price: 18000,
    },
    {
      id: 13,
      brand: 'Mazda',
      model: 'CX-5',
      year: 2020,
      price: 27000,
    },
    {
      id: 14,
      brand: 'Kia',
      model: 'Optima',
      year: 2019,
      price: 23000,
    },
    {
      id: 15,
      brand: 'Nissan',
      model: 'Altima',
      year: 2020,
      price: 26000,
    },
    {
      id: 16,
      brand: 'Jeep',
      model: 'Wrangler',
      year: 2021,
      price: 38000,
    },
    {
      id: 17,
      brand: 'GMC',
      model: 'Sierra',
      year: 2018,
      price: 35000,
    },
    {
      id: 18,
      brand: 'Ram',
      model: '1500',
      year: 2020,
      price: 40000,
    },
    {
      id: 19,
      brand: 'Chrysler',
      model: '300',
      year: 2019,
      price: 28000,
    },
    {
      id: 20,
      brand: 'Dodge',
      model: 'Challenger',
      year: 2021,
      price: 45000,
    },
  ];
  
  export default carData;
  